/*
 * Created on 13 nov 2016 ( Time 20:13:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.cliente.desktop.modelo;

import java.io.Serializable;
import javax.validation.constraints.* ;
import org.hibernate.validator.constraints.*;
import java.util.List;

public class Pantalla implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer    idpantalla   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@NotNull
	@NotBlank
	@Size(max = 255)
    private String     nombre       ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    private List<Permiso> listOfPermiso;

    private List<Perfiles> listOfPerfiles;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Pantalla() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdpantalla( Integer idpantalla ) {
        this.idpantalla = idpantalla ;
    }
    public Integer getIdpantalla() {
        return this.idpantalla;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : Nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfPermiso( List<Permiso> listOfPermiso ) {
        this.listOfPermiso = listOfPermiso;
    }
    public List<Permiso> getListOfPermiso() {
        return this.listOfPermiso;
    }

    public void setListOfPerfiles( List<Perfiles> listOfPerfiles ) {
        this.listOfPerfiles = listOfPerfiles;
    }
    public List<Perfiles> getListOfPerfiles() {
        return this.listOfPerfiles;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idpantalla);
        sb.append("]:"); 
        sb.append(nombre);
        return sb.toString(); 
    } 

}
