/*
 * Created on 13 nov 2016 ( Time 20:13:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.cliente.desktop.modelo;
import java.io.Serializable;


public class PantallapermisosKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    private Integer    idpantalla   ;
    
    private String     idpermiso    ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public PantallapermisosKey() {
        super();
    }

    public PantallapermisosKey( Integer idpantalla, String idpermiso ) {
        super();
        this.idpantalla = idpantalla ;
        this.idpermiso = idpermiso ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setIdpantalla( Integer value ) {
        this.idpantalla = value;
    }
    public Integer getIdpantalla() {
        return this.idpantalla;
    }

    public void setIdpermiso( String value ) {
        this.idpermiso = value;
    }
    public String getIdpermiso() {
        return this.idpermiso;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		PantallapermisosKey other = (PantallapermisosKey) obj; 
		//--- Attribute idpantalla
		if ( idpantalla == null ) { 
			if ( other.idpantalla != null ) 
				return false ; 
		} else if ( ! idpantalla.equals(other.idpantalla) ) 
			return false ; 
		//--- Attribute idpermiso
		if ( idpermiso == null ) { 
			if ( other.idpermiso != null ) 
				return false ; 
		} else if ( ! idpermiso.equals(other.idpermiso) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute idpantalla
		result = prime * result + ((idpantalla == null) ? 0 : idpantalla.hashCode() ) ; 
		//--- Attribute idpermiso
		result = prime * result + ((idpermiso == null) ? 0 : idpermiso.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(idpantalla); 
		sb.append("|"); 
		sb.append(idpermiso); 
        return sb.toString();
    }
}
