/*
 * Created on 13 nov 2016 ( Time 20:13:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.cliente.desktop.modelo;

import java.io.Serializable;
import javax.validation.constraints.* ;
import org.hibernate.validator.constraints.*;
import java.util.List;

public class Perfiles implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer    idperfiles   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@NotNull
	@NotBlank
	@Size(max = 90)
    private String     nombre       ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    private List<Usuario> listOfUsuario;

    private List<Permiso> listOfPermiso;

    private List<Pantalla> listOfPantalla;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Perfiles() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdperfiles( Integer idperfiles ) {
        this.idperfiles = idperfiles ;
    }
    public Integer getIdperfiles() {
        return this.idperfiles;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfUsuario( List<Usuario> listOfUsuario ) {
        this.listOfUsuario = listOfUsuario;
    }
    public List<Usuario> getListOfUsuario() {
        return this.listOfUsuario;
    }

    public void setListOfPermiso( List<Permiso> listOfPermiso ) {
        this.listOfPermiso = listOfPermiso;
    }
    public List<Permiso> getListOfPermiso() {
        return this.listOfPermiso;
    }

    public void setListOfPantalla( List<Pantalla> listOfPantalla ) {
        this.listOfPantalla = listOfPantalla;
    }
    public List<Pantalla> getListOfPantalla() {
        return this.listOfPantalla;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idperfiles);
        sb.append("]:"); 
        sb.append(nombre);
        return sb.toString(); 
    } 

}
