/*
 * Created on 9 oct 2016 ( Time 11:29:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.salondeventas.cliente.desktop.modelo;
import java.io.Serializable;


public class PrecioproductoKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    private Integer    idprecioproducto ;
    
    private Integer    idproducto   ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public PrecioproductoKey() {
        super();
    }

    public PrecioproductoKey( Integer idprecioproducto, Integer idproducto ) {
        super();
        this.idprecioproducto = idprecioproducto ;
        this.idproducto = idproducto ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setIdprecioproducto( Integer value ) {
        this.idprecioproducto = value;
    }
    public Integer getIdprecioproducto() {
        return this.idprecioproducto;
    }

    public void setIdproducto( Integer value ) {
        this.idproducto = value;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		PrecioproductoKey other = (PrecioproductoKey) obj; 
		//--- Attribute idprecioproducto
		if ( idprecioproducto == null ) { 
			if ( other.idprecioproducto != null ) 
				return false ; 
		} else if ( ! idprecioproducto.equals(other.idprecioproducto) ) 
			return false ; 
		//--- Attribute idproducto
		if ( idproducto == null ) { 
			if ( other.idproducto != null ) 
				return false ; 
		} else if ( ! idproducto.equals(other.idproducto) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute idprecioproducto
		result = prime * result + ((idprecioproducto == null) ? 0 : idprecioproducto.hashCode() ) ; 
		//--- Attribute idproducto
		result = prime * result + ((idproducto == null) ? 0 : idproducto.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(idprecioproducto); 
		sb.append("|"); 
		sb.append(idproducto); 
        return sb.toString();
    }
}
