/*
 * Created on 9 oct 2016 ( Time 11:29:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.cliente.desktop.modelo;

import java.io.Serializable;
import javax.validation.constraints.* ;
import org.hibernate.validator.constraints.*;
import java.util.List;

public class Producto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer    idproducto   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
			@NotBlank
	@Size(max = 255)
	    private String     detalle      ;
			@NotBlank
	@Size(max = 90)
	    private String     nombre       ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    private List<Precioproducto> listOfPrecioproducto;

    private List<Lineadeventa> listOfLineadeventa;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Producto() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdproducto( Integer idproducto ) {
        this.idproducto = idproducto ;
    }
    public Integer getIdproducto() {
        return this.idproducto;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : detalle ( VARCHAR ) 
    public void setDetalle( String detalle ) {
        this.detalle = detalle;
    }
    public String getDetalle() {
        return this.detalle;
    }

    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfPrecioproducto( List<Precioproducto> listOfPrecioproducto ) {
        this.listOfPrecioproducto = listOfPrecioproducto;
    }
    public List<Precioproducto> getListOfPrecioproducto() {
        return this.listOfPrecioproducto;
    }

    public void setListOfLineadeventa( List<Lineadeventa> listOfLineadeventa ) {
        this.listOfLineadeventa = listOfLineadeventa;
    }
    public List<Lineadeventa> getListOfLineadeventa() {
        return this.listOfLineadeventa;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idproducto);
        sb.append("]:"); 
        sb.append(detalle);
        sb.append("|");
        sb.append(nombre);
        return sb.toString(); 
    } 

}
