/*
 * Created on 9 oct 2016 ( Time 11:29:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.cliente.desktop.modelo;

import java.io.Serializable;
import javax.validation.constraints.* ;
import org.hibernate.validator.constraints.*;

public class Usuario implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer    idusuario    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@NotBlank(message= "{mensaje.error.notblank.pref} nombre {mensaje.error.vacio.suf}" )
	@Size(max = 45, message = "{mensaje.error.size.pref} nombre {mensaje.error.size.suf} 45.")
	private String     clave        ;
	@NotBlank(message= "{mensaje.error.notblank.pref} nombre {mensaje.error.vacio.suf}" )
	@Size(max = 45, message = "{mensaje.error.size.pref} nombre {mensaje.error.size.suf} 45.")
	private String     nombre       ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Usuario() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdusuario( Integer idusuario ) {
        this.idusuario = idusuario ;
    }
    public Integer getIdusuario() {
        return this.idusuario;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : clave ( VARCHAR ) 
    public void setClave( String clave ) {
        this.clave = clave;
    }
    public String getClave() {
        return this.clave;
    }

    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idusuario);
        sb.append("]:"); 
        sb.append(clave);
        sb.append("|");
        sb.append(nombre);
        return sb.toString(); 
    } 

}
