/*
 * Created on 13 nov 2016 ( Time 20:13:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package org.salondeventas.cliente.desktop.modelo;

import java.io.Serializable;
import javax.validation.constraints.* ;
import org.hibernate.validator.constraints.*;

public class Usuarioperfiles implements Serializable {

    private static final long serialVersionUID = 1L;

    private UsuarioperfilesKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Usuarioperfiles() {
		super();
		this.compositePrimaryKey = new UsuarioperfilesKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setIdusuario( Integer idusuario ) {
        this.compositePrimaryKey.setIdusuario( idusuario ) ;
    }
    public Integer getIdusuario() {
        return this.compositePrimaryKey.getIdusuario() ;
    }
    public void setIdperfil( Integer idperfil ) {
        this.compositePrimaryKey.setIdperfil( idperfil ) ;
    }
    public Integer getIdperfil() {
        return this.compositePrimaryKey.getIdperfil() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
