/*
 * Created on 13 oct 2016 ( Time 09:04:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.salondeventas.cliente.desktop.modelo;

import java.io.Serializable;
import javax.validation.constraints.* ;
import org.hibernate.validator.constraints.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Venta implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer    idventa      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
		    private Date       fecha        ;
		    private Date       fechaPago    ;
		    private BigDecimal total        ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    private List<Lineadeventa> listOfLineadeventa;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Venta() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdventa( Integer idventa ) {
        this.idventa = idventa ;
    }
    public Integer getIdventa() {
        return this.idventa;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : fecha ( DATETIME ) 
    public void setFecha( Date fecha ) {
        this.fecha = fecha;
    }
    public Date getFecha() {
        return this.fecha;
    }

    //--- DATABASE MAPPING : fecha_pago ( DATETIME ) 
    public void setFechaPago( Date fechaPago ) {
        this.fechaPago = fechaPago;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }

    //--- DATABASE MAPPING : total ( DECIMAL ) 
    public void setTotal( BigDecimal total ) {
        this.total = total;
    }
    public BigDecimal getTotal() {
        return this.total;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfLineadeventa( List<Lineadeventa> listOfLineadeventa ) {
        this.listOfLineadeventa = listOfLineadeventa;
    }
    public List<Lineadeventa> getListOfLineadeventa() {
        return this.listOfLineadeventa;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idventa);
        sb.append("]:"); 
        sb.append(fecha);
        sb.append("|");
        sb.append(fechaPago);
        sb.append("|");
        sb.append(total);
        return sb.toString(); 
    } 

}
